import React from 'react'

export const metadata = {
  title: 'Ruta',
  description: 'Generated by Next.js',
}

const RutaPage = () => {
  return (
    <div>RutaPage</div>
  )
}

export default RutaPage