import React from 'react'

export const metadata = {
  title: 'Directorio',
  description: 'Generated by Next.js',
}

const DirectorioPage = () => {
  return (
    <div>DirectorioPage</div>
  )
}

export default DirectorioPage