import Footer from "./components/footer/footer"
import Header from "./components/header/header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header title="React" />
        {children}
        <Footer />        
      </body>
    </html>
  )
}
